// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsfenjymbpkhiiwqbqeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zZmVuanltYnBraGlpd3FicWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1ODAxOTUsImV4cCI6MjA4NjE1NjE5NX0.POjqEIKEL938qRjcJSMOFOLkRUI88o3st3tNjkcNsFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});